name       : peercoin
version    : 0.9.0
release    : 26
source     :
    - https://github.com/peercoin/peercoin/archive/v0.9.0ppc.tar.gz : 95f4d50706f0eb2c14e3f3b149cbb3e7bfbc71ea33ef3e778dc9a477841a35b5
license    : MIT
component  : network.clients
summary    : Peercoin is the first cryptocurrency design introducing proof-of-stake consensus as a security model, with a combined proof-of-stake/proof-of-work minting system.
description: |
    Peercoin is the first cryptocurrency design introducing proof-of-stake consensus as a security model, with a combined proof-of-stake/proof-of-work minting system.

    Peercoin is based on Bitcoin, while introducing many important innovations to cryptocurrency field including new security model, energy efficiency, better minting model and more adaptive response to rapid change in network computation power.
libsplit   : no
replaces   :
    - peerunity
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libevent)
    - pkgconfig(libqrencode)
    - pkgconfig(libssl)
    - pkgconfig(miniupnpc)
    - pkgconfig(protobuf)
    - db4.8-devel
    - db5-devel
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-missing-include.patch

    sed -i 's:/usr/share/pixmaps/peercoin128.png:peercoin:g' contrib/debian/peercoin-qt.desktop
    %autogen --disable-static --enable-upnp-default
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/{bin/bench_bitcoin,include,lib64/pkgconfig}
    install -Dm00644 $workdir/contrib/debian/peercoin-qt.desktop $installdir/usr/share/applications/peercoin-qt.desktop
    install -Dm00644 share/pixmaps/peercoin256.png $installdir/usr/share/pixmaps/peercoin.png
    install -Dm00644 $workdir/contrib/debian/examples/peercoin.conf $installdir/usr/share/doc/peercoin/examples/peercoin.conf
    install -Dm00644 $pkgfiles/peercoind@.service  $installdir/usr/lib/systemd/system/peercoind@.service
