name       : peercoin
version    : 0.7.1
release    : 14
source     :
    - https://github.com/peercoin/peercoin/archive/v0.7.1ppc.tar.gz : 1c2aae8870300f9f56b46e886a6b4501d032e7f0ec85db3e08ab5a2b7cf1090a
license    : MIT
component  : network.clients
summary    : Peercoin is the first cryptocurrency design introducing proof-of-stake consensus as a security model, with a combined proof-of-stake/proof-of-work minting system.
description: |
    Peercoin is the first cryptocurrency design introducing proof-of-stake consensus as a security model, with a combined proof-of-stake/proof-of-work minting system.

    Peercoin is based on Bitcoin, while introducing many important innovations to cryptocurrency field including new security model, energy efficiency, better minting model and more adaptive response to rapid change in network computation power.
replaces   :
    - peerunity
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libevent)
    - pkgconfig(libqrencode)
    - pkgconfig(libssl)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - db4.8-devel
    - db5-devel
    - libboost-devel
    - miniupnpc-devel
libsplit   : no
setup      : |
    sed -i 's:/usr/share/pixmaps/peercoin128.png:peercoin:g' contrib/debian/peercoin-qt.desktop
build      : |
    %qmake \
        BDB_INCLUDE_PATH="/usr/include/db4.8" \
        BDB_LIB_SUFFIX="-4.8" \
        "USE_IPV6=1" \
        "USE_QRCODE=1" \
        "USE_UPNP=1"
    %make
    cd src
    %make -f makefile.unix
install    : |
    install -Dm755 $workdir/peercoin-qt $installdir/usr/bin/peercoin-qt
    install -Dm755 $workdir/src/peercoind $installdir/usr/bin/peercoind
    install -Dm644 $workdir/contrib/debian/peercoin-qt.desktop $installdir/usr/share/applications/peercoin-qt.desktop
    install -Dm644 share/pixmaps/peercoin256.png $installdir/usr/share/pixmaps/peercoin.png
    install -Dm644 $workdir/contrib/debian/examples/peercoin.conf $installdir/usr/share/doc/peercoin/examples/peercoin.conf
    install -Dm644 $pkgfiles/peercoind@.service  $installdir/usr/lib/systemd/system/peercoind@.service
