name       : peercoin
version    : 0.8.2.1
release    : 19
source     :
    - https://github.com/peercoin/peercoin/archive/v0.8.2.1ppc.tar.gz : 323e04ac00cc23b2c4e4cd18283102c8790eeeac9b43006d7acaf33fd594297f
license    : MIT
component  : network.clients
summary    : Peercoin is the first cryptocurrency design introducing proof-of-stake consensus as a security model, with a combined proof-of-stake/proof-of-work minting system.
description: |
    Peercoin is the first cryptocurrency design introducing proof-of-stake consensus as a security model, with a combined proof-of-stake/proof-of-work minting system.

    Peercoin is based on Bitcoin, while introducing many important innovations to cryptocurrency field including new security model, energy efficiency, better minting model and more adaptive response to rapid change in network computation power.
replaces   :
    - peerunity
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libevent)
    - pkgconfig(libqrencode)
    - pkgconfig(libssl)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - db4.8-devel
    - db5-devel
    - libboost-devel
    - miniupnpc-devel
libsplit   : no
setup      : |
    sed -i 's:/usr/share/pixmaps/peercoin128.png:peercoin:g' contrib/debian/peercoin-qt.desktop
    %autogen --disable-static --enable-upnp-default
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/{bin/bench_bitcoin,include,lib64/pkgconfig}
    install -Dm644 $workdir/contrib/debian/peercoin-qt.desktop $installdir/usr/share/applications/peercoin-qt.desktop
    install -Dm644 share/pixmaps/peercoin256.png $installdir/usr/share/pixmaps/peercoin.png
    install -Dm644 $workdir/contrib/debian/examples/peercoin.conf $installdir/usr/share/doc/peercoin/examples/peercoin.conf
    install -Dm644 $pkgfiles/peercoind@.service  $installdir/usr/lib/systemd/system/peercoind@.service
